//! Canonical storage-key paths for all artifact types.
//!
//! Most storage keys used by Shardlake are generated by functions in this
//! module.  Callers in production code must **not** construct new keys by
//! hand; use the helpers here so that the layout stays consistent and can be
//! changed in one place.  Some legacy code and tests still refer to specific
//! keys or prefixes directly and should be migrated over time.
//!
//! # Layout
//!
//! ```text
//! <storage-root>/
//! ├── datasets/
//! │   └── <dataset-version>/
//! │       ├── vectors.jsonl           ← dataset_vectors_key
//! │       ├── metadata.json           ← dataset_metadata_key
//! │       └── info.json               ← dataset_info_key
//! ├── indexes/
//! │   └── <index-version>/
//! │       ├── manifest.json           ← index_manifest_key
//! │       ├── pq_codebook.bin         ← index_pq_codebook_key (PQ builds only)
//! │       ├── coarse_quantizer.cq     ← index_coarse_quantizer_key
//! │       ├── worker_plan.json        ← worker_plan_key (distributed builds)
//! │       ├── shards/
//! │       │   ├── shard-0000.sidx     ← index_shard_key(…, 0)
//! │       │   └── shard-0001.sidx     ← index_shard_key(…, 1)
//! │       └── workers/
//! │           └── <worker-id>/
//! │               └── output.json     ← worker_output_key(…, worker_id)
//! └── aliases/
//!     └── <alias-name>.json           ← alias_key
//! ```

/// Storage key for a dataset's re-serialised vector JSONL file.
pub fn dataset_vectors_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/vectors.jsonl")
}

/// Storage key for a dataset's id → metadata JSON object.
pub fn dataset_metadata_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/metadata.json")
}

/// Storage key for the dataset summary / info pointer written by `shardlake ingest`.
pub fn dataset_info_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/info.json")
}

/// Storage key for the manifest JSON of a given index version.
pub fn index_manifest_key(index_version: &str) -> String {
    format!("indexes/{index_version}/manifest.json")
}

/// Storage-key prefix containing all index artifacts.
pub fn indexes_prefix() -> &'static str {
    "indexes/"
}

/// Storage key for a single shard `.sidx` artifact.
///
/// Shard numbers are zero-padded to four digits so that lexicographic and
/// numeric ordering agree for up to 10 000 shards: `shard-0000.sidx`,
/// `shard-0001.sidx`, …  For `shard_number` ≥ 10 000 the padding expands
/// naturally (`shard-10000.sidx`) without truncation.
pub fn index_shard_key(index_version: &str, shard_number: u32) -> String {
    format!("indexes/{index_version}/shards/shard-{shard_number:04}.sidx")
}

/// Storage key for the PQ codebook artifact of a given index version.
///
/// The codebook is a single binary file that encodes all sub-space centroids
/// trained during a product-quantisation build.  It is referenced by
/// `CompressionConfig.codebook_key` in the manifest and loaded by
/// `IndexSearcher` when searching PQ-compressed indexes.
pub fn index_pq_codebook_key(index_version: &str) -> String {
    format!("indexes/{index_version}/pq_codebook.bin")
}

/// Storage key for the IVF coarse-quantizer artifact of a given index version.
///
/// The `.cq` file stores the trained centroids that constitute the IVF coarse
/// quantizer.  It is written alongside `manifest.json` during `build-index`
/// and is used at query time to route vectors to the nearest cluster shards
/// without loading any `.sidx` file.
pub fn index_coarse_quantizer_key(index_version: &str) -> String {
    format!("indexes/{index_version}/coarse_quantizer.cq")
}

/// Storage key for the BM25 lexical-index artifact of a given index version.
///
/// The `.bm25` file stores a serialised [`Bm25Index`] built alongside the
/// vector shard artifacts.  Its existence is indicated by the
/// `LexicalIndexConfig` field inside the manifest.
///
/// [`Bm25Index`]: shardlake_index::bm25::Bm25Index
pub fn index_lexical_key(index_version: &str) -> String {
    format!("indexes/{index_version}/lexical.bm25")
}

/// Storage key for the worker plan JSON for a distributed index build.
///
/// Written by the plan phase of a distributed build so that individual workers
/// can load their assignment by indexing into the plan's `assignments` list.
pub fn worker_plan_key(index_version: &str) -> String {
    format!("indexes/{index_version}/worker_plan.json")
}

/// Storage key for the intermediate output metadata written by a single worker.
///
/// Each worker writes one `output.json` file containing the list of
/// shard-output descriptors for the shards it built.  The merge step
/// reads these files to assemble the final manifest without re-reading the
/// shard artifact bytes.
pub fn worker_output_key(index_version: &str, worker_id: usize) -> String {
    format!("indexes/{index_version}/workers/{worker_id:04}/output.json")
}

/// Storage key for an alias pointer JSON file.
pub fn alias_key(alias: &str) -> String {
    format!("aliases/{alias}.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dataset_keys_have_stable_layout() {
        assert_eq!(dataset_vectors_key("ds-v1"), "datasets/ds-v1/vectors.jsonl");
        assert_eq!(
            dataset_metadata_key("ds-v1"),
            "datasets/ds-v1/metadata.json"
        );
        assert_eq!(dataset_info_key("ds-v1"), "datasets/ds-v1/info.json");
    }

    #[test]
    fn index_keys_have_stable_layout() {
        assert_eq!(index_manifest_key("idx-v1"), "indexes/idx-v1/manifest.json");
        assert_eq!(indexes_prefix(), "indexes/");
        assert_eq!(
            index_shard_key("idx-v1", 0),
            "indexes/idx-v1/shards/shard-0000.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 1),
            "indexes/idx-v1/shards/shard-0001.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 42),
            "indexes/idx-v1/shards/shard-0042.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 9999),
            "indexes/idx-v1/shards/shard-9999.sidx"
        );
        // Numbers >= 10_000 expand beyond four digits without truncation.
        assert_eq!(
            index_shard_key("idx-v1", 10_000),
            "indexes/idx-v1/shards/shard-10000.sidx"
        );
    }

    #[test]
    fn index_pq_codebook_key_has_stable_layout() {
        assert_eq!(
            index_pq_codebook_key("idx-v1"),
            "indexes/idx-v1/pq_codebook.bin"
        );
    }

    #[test]
    fn index_lexical_key_has_stable_layout() {
        assert_eq!(index_lexical_key("idx-v1"), "indexes/idx-v1/lexical.bm25");
    }

    #[test]
    fn worker_keys_have_stable_layout() {
        assert_eq!(worker_plan_key("idx-v1"), "indexes/idx-v1/worker_plan.json");
        assert_eq!(
            worker_output_key("idx-v1", 0),
            "indexes/idx-v1/workers/0000/output.json"
        );
        assert_eq!(
            worker_output_key("idx-v1", 3),
            "indexes/idx-v1/workers/0003/output.json"
        );
        // Worker IDs >= 10_000 expand beyond four digits without truncation.
        assert_eq!(
            worker_output_key("idx-v1", 10_000),
            "indexes/idx-v1/workers/10000/output.json"
        );
    }

    #[test]
    fn alias_key_has_stable_layout() {
        assert_eq!(alias_key("latest"), "aliases/latest.json");
        assert_eq!(alias_key("production"), "aliases/production.json");
    }
}
