//! Canonical storage-key paths for all artifact types.
//!
//! Most storage keys used by Shardlake are generated by functions in this
//! module.  Callers in production code must **not** construct new keys by
//! hand; use the helpers here so that the layout stays consistent and can be
//! changed in one place.  Some legacy code and tests still refer to specific
//! keys or prefixes directly and should be migrated over time.
//!
//! # Layout
//!
//! ```text
//! <storage-root>/
//! ├── datasets/
//! │   └── <dataset-version>/
//! │       ├── vectors.jsonl      ← dataset_vectors_key
//! │       ├── metadata.json      ← dataset_metadata_key
//! │       └── info.json          ← dataset_info_key
//! ├── indexes/
//! │   └── <index-version>/
//! │       ├── manifest.json      ← index_manifest_key
//! │       └── shards/
//! │           ├── shard-0000.sidx  ← index_shard_key(…, 0)
//! │           └── shard-0001.sidx  ← index_shard_key(…, 1)
//! └── aliases/
//!     └── <alias-name>.json      ← alias_key
//! ```

/// Storage key for a dataset's re-serialised vector JSONL file.
pub fn dataset_vectors_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/vectors.jsonl")
}

/// Storage key for a dataset's id → metadata JSON object.
pub fn dataset_metadata_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/metadata.json")
}

/// Storage key for the dataset summary / info pointer written by `shardlake ingest`.
pub fn dataset_info_key(dataset_version: &str) -> String {
    format!("datasets/{dataset_version}/info.json")
}

/// Storage key for the manifest JSON of a given index version.
pub fn index_manifest_key(index_version: &str) -> String {
    format!("indexes/{index_version}/manifest.json")
}

/// Storage-key prefix containing all index artifacts.
pub fn indexes_prefix() -> &'static str {
    "indexes/"
}

/// Storage key for a single shard `.sidx` artifact.
///
/// Shard numbers are zero-padded to four digits so that lexicographic and
/// numeric ordering agree for up to 10 000 shards: `shard-0000.sidx`,
/// `shard-0001.sidx`, …  For `shard_number` ≥ 10 000 the padding expands
/// naturally (`shard-10000.sidx`) without truncation.
pub fn index_shard_key(index_version: &str, shard_number: u32) -> String {
    format!("indexes/{index_version}/shards/shard-{shard_number:04}.sidx")
}

/// Storage key for an alias pointer JSON file.
pub fn alias_key(alias: &str) -> String {
    format!("aliases/{alias}.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dataset_keys_have_stable_layout() {
        assert_eq!(dataset_vectors_key("ds-v1"), "datasets/ds-v1/vectors.jsonl");
        assert_eq!(
            dataset_metadata_key("ds-v1"),
            "datasets/ds-v1/metadata.json"
        );
        assert_eq!(dataset_info_key("ds-v1"), "datasets/ds-v1/info.json");
    }

    #[test]
    fn index_keys_have_stable_layout() {
        assert_eq!(index_manifest_key("idx-v1"), "indexes/idx-v1/manifest.json");
        assert_eq!(indexes_prefix(), "indexes/");
        assert_eq!(
            index_shard_key("idx-v1", 0),
            "indexes/idx-v1/shards/shard-0000.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 1),
            "indexes/idx-v1/shards/shard-0001.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 42),
            "indexes/idx-v1/shards/shard-0042.sidx"
        );
        assert_eq!(
            index_shard_key("idx-v1", 9999),
            "indexes/idx-v1/shards/shard-9999.sidx"
        );
        // Numbers >= 10_000 expand beyond four digits without truncation.
        assert_eq!(
            index_shard_key("idx-v1", 10_000),
            "indexes/idx-v1/shards/shard-10000.sidx"
        );
    }

    #[test]
    fn alias_key_has_stable_layout() {
        assert_eq!(alias_key("latest"), "aliases/latest.json");
        assert_eq!(alias_key("production"), "aliases/production.json");
    }
}
